<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UserSecretsId>464549b7-0236-49b6-a420-d634d0bb73bc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.EncryptColumn" Version="6.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NodaTime" Version="3.1.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\ATS\" />
    <Folder Include="Repositories\ATS\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATS.Models\ATS.Models.csproj" />
    <ProjectReference Include="..\HRIS.Models\HRIS.Models.csproj" />
  </ItemGroup>

</Project>
