using RGO.Models.Enums;

namespace RGO.Models;

public record EmployeeDto(
    int Id,
    string EmployeeNumber,
    string TaxNumber,
    DateOnly EngagementDate,
    DateOnly? TerminationDate,
    EmployeeDto? ReportingLine,
    bool Disability,
    string DisabilityNotes,
    int Level,
    EmployeeTypeDto? EmployeeType,
    string Notes,
    float LeaveInterval,
    float SalaryDays, 
    float PayRate,
    int Salary, 
    string Title,
    string Name,
    string Initials,
    string Surname,
    DateOnly DateOfBirth,
    string CountryOfBirth,
    string Nationality,
    string? IdNumber,
    string? PassportNumber,
    DateOnly? PassportExpirationDate,
    string? PassportCountryIssue,
    Race Race,
    Gender Gender,
    string Photo,
    string Email,
    string PersonalEmail,
    string CellphoneNo);
