using RGO.Models.Enums;

namespace RGO.Models;

public record EmployeeDto(
    int Id,
    string EmployeeNumber,
    string TaxNumber,
    DateTime EngagementDate,
    DateTime TerminationDate,
    int? ReportingLine,
    bool Disability,
    string DisabilityNotes,
    int Level,
    EmployeeTypeDto EmployeeType,
    string Notes,
    float LeaveInterval,
    float SalaryDays, 
    float PayRate,
    int Salary, 
    string Title,
    string Name,
    string Initials,
    string Surname,
    DateTime DateOfBirth,
    string CountryOfBirth,
    string Nationality,
    string IdNumber,
    string PassportNumber,
    DateTime PassportExpirationDate,
    string PassportCountryIssue,
    Race Race,
    Gender Gender,
    string Photo,
    string PersonalEmail,
    string CellphoneNo);
